name: Comunicador de la Legión

on:
  workflow_dispatch:
    inputs:
      villano:
        description: '¿Qué villano envía el mensaje?'
        required: true
        type: choice
        options:
          - Magneto
          - Joker
          - Mystic
          - Brainiac

jobs:
  transmitir_mensaje:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4