name: Comunicador de la Legión

on:
  workflow_dispatch:
    inputs:
      villano:
        description: '¿Qué villano envía el mensaje?'
        required: true
        type: choice
        options:
          - Magneto
          - Joker
          - Mystic
          - Brainiac
      mensaje:
        description: 'mensaje para el consejo'
        required: true
        default: 'la misión fue un éxito'
      prioridad:
        description: 'nivel de prioridad'
        required: true
        type: choice
        options:
          - normal
          - alta
          - crítica

jobs:
  transmitir_mensaje:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar el transmisor de la legión
        run: sudo apt-get install -y cowsay

      - name: Imprimir inputs
        run: |
          echo "Inputs: "
          echo ""
          echo "Villano: ${{ inputs.villano }}"
          echo "Nivel: ${{ inputs.prioridad }}"

          echo "Mensaje"
          cowsay -f eyes "${{ inputs.mensaje }}"